//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dilizity.API.Security {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MessageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dilizity.API.Security.MessageResource", typeof(MessageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account is Locked.
        /// </summary>
        public static string Dilizity_ChangePassword_Account_Locked {
            get {
                return ResourceManager.GetString("Dilizity_ChangePassword_Account_Locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password Failed.
        /// </summary>
        public static string Dilizity_ChangePassword_Exception_Change_Password_failed {
            get {
                return ResourceManager.GetString("Dilizity_ChangePassword_Exception_Change_Password_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password can&apos;t reuse.
        /// </summary>
        public static string Dilizity_ChangePassword_Exception_Password_Cant_Reuse {
            get {
                return ResourceManager.GetString("Dilizity_ChangePassword_Exception_Password_Cant_Reuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Failed.
        /// </summary>
        public static string Dilizity_ChangePassword_Login_Failed {
            get {
                return ResourceManager.GetString("Dilizity_ChangePassword_Login_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password matched.
        /// </summary>
        public static string Dilizity_ChangePassword_PasswordMatch {
            get {
                return ResourceManager.GetString("Dilizity_ChangePassword_PasswordMatch", resourceCulture);
            }
        }
    }
}
