--DROP TABLE [dbo].[RPT_REPORT_MENU];
--DROP TABLE [dbo].[RPT_REPORT_FILTERS];
--DROP TABLE [dbo].[RPT_REPORT_COLUMNS];
--DROP TABLE [dbo].[RPT_REPORT];
--DROP TABLE [dbo].[RPT_REPORT_DATA_SOURCE];


CREATE TABLE RPT_REPORT_MENU
(
	REPORT_MENU_ID INT IDENTITY PRIMARY KEY,
	PARENT_ID INT NULL REFERENCES RPT_REPORT_MENU(REPORT_MENU_ID),
	DISPLAY_NAME NVARCHAR(100) NOT NULL UNIQUE,
	URL NVARCHAR(2000) NULL,
	PERMISSION_ID INT NULL REFERENCES SEC_PERMISSION(PERMISSION_ID),
	IS_SYSTEM INT NULL,
	IS_DELETED INT NULL,
	[CREATED_ON] [datetime] NOT NULL DEFAULT GetDate(),
	[CREATED_BY] [nvarchar](100) NOT NULL,
	[UPDATED_ON] [datetime] NOT NULL DEFAULT GetDate(),
	[UPDATED_BY] [nvarchar](100) NULL
);

CREATE TABLE RPT_REPORT_DATA_SOURCE
(
	REPORT_DATA_SOURCE_ID INT IDENTITY PRIMARY KEY,
	DATA_SOURCE_NAME NVARCHAR(400) NOT NULL UNIQUE,
	CONNECTION_STRING NVARCHAR(2000) NOT NULL,
	PROVIDER_NAME NVARCHAR(400) NOT NULL,
	IS_SYSTEM INT NULL,
	IS_DELETED INT NULL,
	[CREATED_ON] [datetime] NOT NULL DEFAULT GetDate(),
	[CREATED_BY] [nvarchar](100) NOT NULL,
	[UPDATED_ON] [datetime] NOT NULL DEFAULT GetDate(),
	[UPDATED_BY] [nvarchar](100) NULL
);

--DROP TABLE RPT_REPORT
--DROP TABLE RPT_REPORT_FILTERS
--DROP TABLE RPT_REPORT_COLUMNS
CREATE TABLE RPT_REPORT
(  
	REPORT_ID INT IDENTITY PRIMARY KEY,
	SYSTEM_NAME NVARCHAR(250) UNIQUE,
	DISPLAY_NAME NVARCHAR(250) UNIQUE,
	REPORT_DATA_SOURCE_ID INT NOT NULL REFERENCES RPT_REPORT_DATA_SOURCE(REPORT_DATA_SOURCE_ID),
	QUERY NVARCHAR(MAX) NOT NULL,
	REPORT_PERMISSION_ID INT NOT NULL REFERENCES SEC_PERMISSION(PERMISSION_ID),
	IS_SYSTEM INT NULL,
	IS_DELETED INT NULL,
	[CREATED_ON] [datetime] NOT NULL DEFAULT GetDate(),
	[CREATED_BY] [nvarchar](100) NOT NULL,
	[UPDATED_ON] [datetime] NOT NULL DEFAULT GetDate(),
	[UPDATED_BY] [nvarchar](100) NULL
);

CREATE TABLE RPT_REPORT_FILTERS
(  
	REPORT_FILTERS_ID INT IDENTITY PRIMARY KEY,
	REPORT_ID INT NOT NULL REFERENCES RPT_REPORT(REPORT_ID),
	FILTER_NAME NVARCHAR(250) NOT NULL,
	DISPLAY_NAME NVARCHAR(250) NOT NULL,
	PLACE_HOLDER NVARCHAR(500) NULL,
	TEMPLATE_OPTION_TYPE INT NULL,
	REPORT_DATA_SOURCE_ID INT NULL REFERENCES RPT_REPORT_DATA_SOURCE(REPORT_DATA_SOURCE_ID),
	FILTER_TYPE_ID INT NOT NULL,
	FILTER_DATA_TYPE_ID INT NOT NULL,
	FILTER_DATA_SOURCE_QUERY NVARCHAR(MAX),
	IS_MANDATORY INT NULL,
	IS_SYSTEM INT NULL,
	IS_DELETED INT NULL,
	[CREATED_ON] [datetime] NOT NULL DEFAULT GetDate(),
	[CREATED_BY] [nvarchar](100) NOT NULL,
	[UPDATED_ON] [datetime] NOT NULL DEFAULT GetDate(),
	[UPDATED_BY] [nvarchar](100) NULL
);

--DROP TABLE RPT_REPORT_COLUMNS

CREATE TABLE RPT_REPORT_COLUMNS
(  
	REPORT_COLUMNS_ID INT IDENTITY PRIMARY KEY,
	REPORT_ID INT NOT NULL REFERENCES RPT_REPORT(REPORT_ID),
	COLUMN_NAME NVARCHAR(250) NOT NULL UNIQUE,
	DISPLAY_NAME NVARCHAR(250) NOT NULL UNIQUE,
	MASKING_FILTER_ID INT  NULL,
	COLUMN_PERMISSION_NAME NVARCHAR(200) NULL,
	IS_SYSTEM INT NULL,
	IS_DELETED INT NULL,
	[CREATED_ON] [datetime] NOT NULL DEFAULT GetDate(),
	[CREATED_BY] [nvarchar](100) NOT NULL,
	[UPDATED_ON] [datetime] NOT NULL DEFAULT GetDate(),
	[UPDATED_BY] [nvarchar](100) NULL
);

CREATE TABLE RPT_REPORT_SYSTEM_FIELDS
(  
	REPORT_SYSTEM_FIELDS_ID INT IDENTITY PRIMARY KEY,
	FIELD_NAME NVARCHAR(250) NOT NULL,
	DISPLAY_NAME NVARCHAR(250) NULL,
	PLACE_HOLDER NVARCHAR(500) NULL,
	TEMPLATE_OPTION_TYPE INT NULL,
	FILTER_TYPE_ID INT NOT NULL,
	IS_DELETED INT NULL,
	[CREATED_ON] [datetime] NOT NULL DEFAULT GetDate(),
	[CREATED_BY] [nvarchar](100) NOT NULL,
	[UPDATED_ON] [datetime] NOT NULL DEFAULT GetDate(),
	[UPDATED_BY] [nvarchar](100) NULL
);

--DROP TABLE RPT_REPORT_SYSTEM_FIELDS

