DROP VIEW SEC_VW_DISTINCT_USER_PERMISSION;

CREATE VIEW SEC_VW_DISTINCT_USER_PERMISSION
AS
SELECT  DISTINcT U.LOGIN_ID, RP.PERMISSION_ID,P.PARENT_PERMISSION_ID, P.SYSTEM_NAME, P.PERMISSION_NAME
FROM	SEC_USER U
		INNER JOIN SEC_USER_ROLE UR ON U.USER_ID = UR.USER_ID
		INNeR JOIn SEC_ROLE_PERMISSION RP ON UR.ROLE_ID = RP.ROLE_ID
		INNER JOIN SEC_PERMISSION P ON RP.PERMISSION_ID = P.PERMISSION_ID And P.IS_DELETED = 0
GO



--DROP VIEW VW_PERMISSION_HIERARCHY
CREATE VIEW dbo.VW_PERMISSION_HIERARCHY AS
WITH WF ( Permission_id, PARENT_PERMISSION_ID, PERMISSION_NAME, SYSTEM_NAME  )
AS
(
SELECT	Permission_id, PARENT_PERMISSION_ID , P.PERMISSION_NAME, P.SYSTEM_NAME
from	SEC_PERMISSION P
WHERE   P.PARENT_PERMISSION_ID is null
UNION ALL
SELECT	P.Permission_id, P.PARENT_PERMISSION_ID, P.PERMISSION_NAME, P.SYSTEM_NAME
from	SEC_PERMISSION P
		INNER JOIN WF ON P.PARENT_PERMISSION_ID = WF.Permission_id 
)
SELECT PERMISSION_ID, PARENT_PERMISSION_ID,  PERMISSION_NAME, dbo.FN_GET_FRIENDLY_PERMISSION_NAME(SYSTEM_NAME) USER_FRIENDLY_NAME
FROM	WF

GO