/****** Object:  StoredProcedure [dbo].[SP_BUSINESS_DELETE_PERMISSION_HIGHRARCHY]    Script Date: 2/22/2017 8:21:21 PM ******/
DROP PROCEDURE [dbo].[SP_BUSINESS_DELETE_PERMISSION_HIGHRARCHY]
GO

-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE PROCEDURE [dbo].[SP_BUSINESS_DELETE_PERMISSION_HIGHRARCHY]
	@SYSTEM_NAME NVARCHAR(100)
AS
BEGIN
	SET NOCOUNT ON;

	DECLARE @TBL TABLE
	(
		Permission_id INT
	);

	WITH WF 
	AS
	(
	SELECT	[Level]=1, Permission_id, PARENT_PERMISSION_ID
	from	SEC_PERMISSION P
	WHERE   P.SYSTEM_NAME = @SYSTEM_NAME
	UNION ALL
	SELECT	[Level]+1, P.Permission_id, P.PARENT_PERMISSION_ID
	from	SEC_PERMISSION P
			INNER JOIN WF ON P.PARENT_PERMISSION_ID  = WF.Permission_id
	)
	INSERT INTO @TBL(Permission_id)
	SELECT Permission_id
	FROM	WF
	ORDER BY 1 desc

	DELETE FROM SEC_ROLE_PERMISSION
	WHERE PERMISSION_ID IN (SELECT PERMISSION_ID FROM @TBL);

	DELETE FROM WORK_FLOW_ACTION
	WHERE PERMISSION_ID IN (SELECT PERMISSION_ID FROM @TBL);

	DELETE FROM SEC_SIDEBAR_MENU
	WHERE PERMISSION_ID IN (SELECT PERMISSION_ID FROM @TBL);
	
	DELETE FROM SEC_PERMISSION
	WHERE PERMISSION_ID IN (SELECT PERMISSION_ID FROM @TBL);
	
END

GO


