IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[VW_MAKER_LIST]'))
DROP VIEW [dbo].[VW_MAKER_LIST]
GO

CREATE VIEW [dbo].[VW_MAKER_LIST] AS
SELECT  MAKER_ID,
		ML.PERMISSION_ID,
		P.SYSTEM_NAME,
		DATA,
		STATUS,
		OBJECT_ID,
		ML.IS_DELETED
FROM	MAKER_LIST ML
		INNER JOIN SEC_PERMISSION P ON ML.PERMISSION_ID = P.PERMISSION_ID


GO

IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[VW_WORK_FLOW]'))
DROP VIEW [VW_WORK_FLOW]
GO

CREATE VIEW [dbo].[VW_WORK_FLOW] AS
SELECT  WORK_FLOW_ACTION_ID,
		WFA.PERMISSION_ID,
		P.SYSTEM_NAME,
		SYSTEM_TYPE,
		SYSTEM_ASSEMBLY,
		VERSION,
		ACTION_ORDER,
		IS_ERROR_TOLERANT,
		EXECUTION_BEHAVIOR
FROM	WORK_FLOW_ACTION WFA
		INNER JOIN SEC_PERMISSION P ON WFA.PERMISSION_ID = P.PERMISSION_ID


GO


